const profile = {
    first_name: "Keo Ponleou",
    preferred_name: "Ponleou",
    last_name: "Sok",
    role: "Software engineer",
    hobby: "FOSS developer",
    status: "Open to Opportunities!",
    stack: ["C/C++", "TypeScript", "Python"],
    languages: [
        "React.js",
        "Vue.js",
        "HTML/CSS",
        "JavaScript",
        "TypeScript",
        "Node.js",
        "Python",
        "Ruby",
        "C/C++",
        "PHP",
        "C#",
        "Ruby on Rails",
        "Docker",
        "Wordpress",
    ],
    experience_start: new Date(2021, 0),
    uni: "Deakin University",
    degree: "Bachelors of Computer Science",
    major: "Internet of Things",
    wam: 89,
    grad_date: new Date(2027, 5), // june 2027
    location_state: "Melbourne",
    location_country: "Australia",
    os: "Arch Linux",
    os_arch: "x86_64",
    wm: "SwayFX",
    dotfiles: "https://codeberg.org/ponleou/dotfiles",
};

export default profile;
