import { educations } from "./education";

const profile = {
    first_name: "Keo Ponleou",
    preferred_name: "Ponleou",
    last_name: "Sok",
    role: "Software engineer",
    hobby: "FOSS developer",
    status: "Open to Opportunities!",
    stack: ["C/C++", "TypeScript", "Python"],
    languages: [
        "React.js",
        "Vue.js",
        "HTML/CSS",
        "JavaScript",
        "TypeScript",
        "Node.js",
        "Python",
        "Ruby",
        "C/C++",
        "PHP",
        "C#",
        "Ruby on Rails",
        "Docker",
        "Wordpress",
    ],
    experience_start: new Date(2021, 0),
    uni: educations[0].institution,
    degree: educations[0].name,
    major: educations[0].subname || "N/A",
    wam: educations[0].grade || -1,
    grad_date: educations[0].endDate,
    location_state: "Melbourne",
    location_country: "Australia",
    os: "Arch Linux",
    os_arch: "x86_64",
    wm: "SwayFX",
    dotfiles: "https://codeberg.org/ponleou/dotfiles",
};

export default profile;
